chore: Converting message and proposal fields to generics
sygmaprotocol/sygma-core pull request #19
Opened 2023-12-11 09:37 UTC by mj52951

Changed data field inside message and proposal from `interface{}` to a generic type. 

Closes: #18

2024-01-03 10:24 UTC, mpetrun5 approved these changes

2024-01-03 10:25 UTC, mpetrun5 commented
@MakMuftic Can you please also check this?

2024-01-04 08:47 UTC, mpetrun5 requested changes
Remove unnecessary generics

2024-01-04 09:33 UTC, mpetrun5 approved these changes

2024-01-04 10:03 UTC, MakMuftic approved these changes

2024-01-04 10:04 UTC, merged